### ISSUE TITLE
Hey!  Just a little Readme fix needed!

### ISSUE THREAD

**Issue by Aerodin** [beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater#1]
Hi!  Love your script!   I got it working perfectly.  Just a quick note that the Readme lists the following which I believe is an error under "3. Create scheduled task"

Incorrect in Readme:
/system script run firmware-updater; 

Correct in Command copy/paste and Screenshot:
/system script run Duckdns-Dynamic-IP-Updater;

**Comment by beeyev** [comment]
Thank you!
I have fixed this 
https://github.com/beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater/commit/9cab81f06049dd7d5056a37f9637d3099c0a9d8e
