### ISSUE TITLE
Support multiple interfaces

### ISSUE THREAD

**Issue by r3d1r** [beeyev/Mikrotik-Duckdns-Dynamic-IP-Updater#3]
Hi.
Is it possible to support multiple interfaces ?
In other words, in location with multiple internet connections, select which interface will be used to get the IP ?
Thanks in advance.

**Comment by beeyev** [comment]
Could you please provide an example of the behavior using mikrotik cli ?

**Comment by r3d1r** [comment]
Hey.
I'm not exactly a mikrotik guy.
I only configure mine once in a while, when needed.
Could you please instruct how I can generate the sample?

**Comment by r3d1r** [comment]
Is it possible to force this command to run over an specific interface ?
   _`([/tool_ fetch url=$ipDetectService1 output=user as-value]->"data")`'_
Or this ?
    _`:put [/ip cloud get public-address]`_
Or this ?
    _`:return [:resolve myip.opendns.com server=208.67.222.222]`_

**Comment by beeyev** [comment]
You can just modify the script as you need, and use it the way you like.
